name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Build sdist + wheel
        run: |
          uv sync --dev
          uv build

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: sonictune-${{ github.ref_name }}.flatpak
          manifest-path: flatpak/org.sonicTune.json

      - name: Upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
            sonictune-*.flatpak
          generate_release_notes: true
          draft: true
          prerelease: ${{ contains(github.ref_name, '-') }}
